-----Create Index----
CREATE INDEX EMOB.IDX_OTH_BRAN_TRAN_DOC_DATE ON EMOB.MB_OTH_BRANCH_TRAN
(DOC_DATE); 
/
CREATE INDEX EMOB.IDX_DATE ON EMOB.BEARER_TRAN_INFO
(CREATE_DATE);
/
CREATE INDEX IDX_TOKEN_LOG_CREATE_DATE
    ON EMOB.MB_TRAN_TOKEN (trunc(CREATE_DATE));
/

CREATE INDEX IDX_TRANSFER_LOG_USER_TRAN
    ON EMOB.MB_TRAN_TOKEN (CREATE_BY, TRAN_FLAG);
	

WITH
    BEAR_TRAN_INFO	AS (SELECT DOC_NUM, BEARER_NAME, MOLIBE_NO, LENGTH (NID_PHOTO)    UPLOAD_LENGTH 	
                        FROM EMOB.BEARER_TRAN_INFO 
                        WHERE CREATE_DATE <= :P825_TO_DATE +1 ),
    AGENT_POINT 	AS (SELECT FINACLE_ID || '-' || INITCAP (POINT_NAME)  FINACLE_ID, 
							   POINT_ID 	        FROM EMOB.ST_AGENT_POINT),
    USER_POINT 		AS (SELECT AGENT_POINT_ID POINT_ID, 
						UPPER (user_code) USER_CODE FROM GUMS.MB_USER_MST),
    ACCOUNT_MST 	AS (SELECT AC_NO,   AC_TITLE 	FROM EMOB.MB_ACCOUNT_MST),
    OTHER_BRANCH 	AS (SELECT DOC_NUM, AC_TITLE 	FROM EMOB.MB_OTH_BRANCH_TRAN WHERE DOC_DATE <= :P825_TO_DATE )
	
SELECT CASE WHEN bti.doc_num IS NOT NULL THEN 'Bearer' ELSE 'Self' END AS TRANSACTION_MODE,
       a.MOBILE_NO 							AS TOKEN_GENRATE_MOBILE_NUMBER,
       bti.BEARER_NAME 						AS BEARER_NAME,
       bti.MOLIBE_NO						AS BEARER_MOLIBE_NO,
       ap.FINACLE_ID 						AS FINACLE_ID,
       a.CREATE_BY 							AS TOKEN_GENERATED_BY,
       a.CREATE_DATE						AS TOKEN_GENERATED_DATE_TIME,
       a.AC_NO								AS CR_AC_NO,
       NVL (acm.AC_TITLE, otb.AC_TITLE) 	AS AC_TITLE,
       a.AMOUNT 							AS AMOUNT,
	   DOC_NO 								AS TRANSACTION_NUMBER,
       CASE WHEN PKG_PROCESS_CBS_TRANSACTION.FNC_RET_TYPE (a.AC_NO)='C' THEN 'Conventional' 
			WHEN PKG_PROCESS_CBS_TRANSACTION.FNC_RET_TYPE (a.AC_NO)='I' THEN 'Islamic' 
									END 	AS CBS_TYPE,
       CASE WHEN a.TRAN_FLAG = 'Y'  THEN 'Successful' 
			WHEN a.TRAN_FLAG = 'N'  THEN 'Unsuccessful'  
									END 	AS TRAN_STATUS,
       CASE WHEN UPLOAD_LENGTH > 0  THEN 'Yes' ELSE 'No' 
									END 	AS BEARER_DOC_UPLOAD_STATUS
  FROM EMOB.MB_TRAN_TOKEN  a
       LEFT JOIN BEAR_TRAN_INFO bti ON (a.DOC_NO    = bti.DOC_NUM)
       LEFT JOIN USER_POINT UP 		ON (a.CREATE_BY = UP.USER_CODE)
       LEFT JOIN AGENT_POINT ap 	ON (ap.POINT_ID = UP.POINT_ID AND ap.POINT_ID = DECODE (:P825_POINT_ID ,0, ap.POINT_ID ,:P825_POINT_ID))
       LEFT JOIN ACCOUNT_MST acm 	ON (a.AC_NO     = acm.AC_NO)
       LEFT JOIN OTHER_BRANCH otb 	ON (a.DOC_NO    = otb.DOC_NUM) 
       WHERE  trunc(a.CREATE_DATE)  >= :P825_FROM_DATE 
         AND  trunc(a.CREATE_DATE)  <= :P825_TO_DATE 